[package]
name = "rust-simplicity"
version = "0.1.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "bitcoin" ]

[lib]
name = "simplicity"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies.bitcoin]
version = "0.23"
optional = true

[dependencies]
bitcoin_hashes = "0.7"
byteorder = "1.3"

